# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/archive/v1/audit_log.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Optional

import betterproto


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: Optional[str] = betterproto.string_field(
        1, optional=True, group="_description"
    )
