# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/extensions/v1/audit_log.proto, com/coralogix/extensions/v1/extension.proto, com/coralogix/extensions/v1/extension_deployment_service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List, Optional
from betterproto.grpc.grpclib_client import MetadataLike

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: Optional[str] = betterproto.string_field(
        1, optional=True, group="_description"
    )


@dataclass(eq=False, repr=False)
class Extension(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    image: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    dark_mode_image: Optional[str] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    revisions: List["Revision"] = betterproto.message_field(5)
    is_hidden: Optional[bool] = betterproto.message_field(
        6, wraps=betterproto.TYPE_BOOL
    )
    integrations: List[str] = betterproto.string_field(7)
    keywords: List[str] = betterproto.string_field(8)
    deprecation: "Deprecation" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class Revision(betterproto.Message):
    version: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    description: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    excerpt: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    labels: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    integration_details: List["IntegrationDetail"] = betterproto.message_field(5)
    summary: "RevisionSummary" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class RevisionSummary(betterproto.Message):
    item_counts: "ItemCounts" = betterproto.message_field(1)
    is_new: Optional[bool] = betterproto.message_field(2, wraps=betterproto.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class ItemCounts(betterproto.Message):
    total: int = betterproto.int32_field(1)
    active: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class IntegrationDetail(betterproto.Message):
    name: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class Deprecation(betterproto.Message):
    reason: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    replacement: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class GetDeployedExtensionsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetDeployedExtensionsResponse(betterproto.Message):
    deployed_extensions: List["GetDeployedExtensionsResponseDeployedExtension"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class GetDeployedExtensionsResponseDeployedExtensionSummary(betterproto.Message):
    deployed_item_counts: "ItemCounts" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetDeployedExtensionsResponseDeployedExtension(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    applications: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    item_ids: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )
    summary: "GetDeployedExtensionsResponseDeployedExtensionSummary" = (
        betterproto.message_field(6)
    )


@dataclass(eq=False, repr=False)
class ExtensionDeployment(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    item_ids: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    applications: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class DeployExtensionRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    item_ids: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    applications: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )
    extension_deployment: Optional["ExtensionDeployment"] = betterproto.message_field(
        6, optional=True, group="_extension_deployment"
    )


@dataclass(eq=False, repr=False)
class DeployExtensionResponse(betterproto.Message):
    extension_deployment: "ExtensionDeployment" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class UpdateExtensionRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    item_ids: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    applications: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )
    extension_deployment: Optional["ExtensionDeployment"] = betterproto.message_field(
        6, optional=True, group="_extension_deployment"
    )


@dataclass(eq=False, repr=False)
class UpdateExtensionResponse(betterproto.Message):
    extension_deployment: "ExtensionDeployment" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class UndeployExtensionRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    kept_extension_items: List[Optional[str]] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class UndeployExtensionResponse(betterproto.Message):
    failed_items: List["UndeployExtensionResponseFailedItem"] = (
        betterproto.message_field(1)
    )
    extension_deployment: Optional["ExtensionDeployment"] = betterproto.message_field(
        2, optional=True, group="_extension_deployment"
    )


@dataclass(eq=False, repr=False)
class UndeployExtensionResponseFailedItem(betterproto.Message):
    item_id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    remote_id: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    reason: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)


class ExtensionDeploymentServiceStub(betterproto.ServiceStub):
    async def get_deployed_extensions(self, metadata: Optional[MetadataLike] = None) -> "GetDeployedExtensionsResponse":

        request = GetDeployedExtensionsRequest()

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/GetDeployedExtensions",
            request,
            GetDeployedExtensionsResponse, metadata=metadata
        )

    async def deploy_extension(
        self,
        *,
        id: Optional[str] = None,
        version: Optional[str] = None,
        item_ids: Optional[List[Optional[str]]] = None,
        applications: Optional[List[Optional[str]]] = None,
        subsystems: Optional[List[Optional[str]]] = None,
        extension_deployment: Optional["ExtensionDeployment"] = None
    ) -> "DeployExtensionResponse":
        item_ids = item_ids or []
        applications = applications or []
        subsystems = subsystems or []

        request = DeployExtensionRequest()
        if id is not None:
            request.id = id
        if version is not None:
            request.version = version
        if item_ids is not None:
            request.item_ids = item_ids
        if applications is not None:
            request.applications = applications
        if subsystems is not None:
            request.subsystems = subsystems
        if extension_deployment is not None:
            request.extension_deployment = extension_deployment

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/DeployExtension",
            request,
            DeployExtensionResponse,
        )

    async def update_extension(
        self,
        *,
        id: Optional[str] = None,
        version: Optional[str] = None,
        item_ids: Optional[List[Optional[str]]] = None,
        applications: Optional[List[Optional[str]]] = None,
        subsystems: Optional[List[Optional[str]]] = None,
        extension_deployment: Optional["ExtensionDeployment"] = None
    ) -> "UpdateExtensionResponse":
        item_ids = item_ids or []
        applications = applications or []
        subsystems = subsystems or []

        request = UpdateExtensionRequest()
        if id is not None:
            request.id = id
        if version is not None:
            request.version = version
        if item_ids is not None:
            request.item_ids = item_ids
        if applications is not None:
            request.applications = applications
        if subsystems is not None:
            request.subsystems = subsystems
        if extension_deployment is not None:
            request.extension_deployment = extension_deployment

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/UpdateExtension",
            request,
            UpdateExtensionResponse,
        )

    async def undeploy_extension(
        self,
        *,
        id: Optional[str] = None,
        kept_extension_items: Optional[List[Optional[str]]] = None
    ) -> "UndeployExtensionResponse":
        kept_extension_items = kept_extension_items or []

        request = UndeployExtensionRequest()
        if id is not None:
            request.id = id
        if kept_extension_items is not None:
            request.kept_extension_items = kept_extension_items

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/UndeployExtension",
            request,
            UndeployExtensionResponse,
        )


class ExtensionDeploymentServiceBase(ServiceBase):

    async def get_deployed_extensions(self) -> "GetDeployedExtensionsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deploy_extension(
        self,
        id: Optional[str],
        version: Optional[str],
        item_ids: Optional[List[Optional[str]]],
        applications: Optional[List[Optional[str]]],
        subsystems: Optional[List[Optional[str]]],
        extension_deployment: Optional["ExtensionDeployment"],
    ) -> "DeployExtensionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_extension(
        self,
        id: Optional[str],
        version: Optional[str],
        item_ids: Optional[List[Optional[str]]],
        applications: Optional[List[Optional[str]]],
        subsystems: Optional[List[Optional[str]]],
        extension_deployment: Optional["ExtensionDeployment"],
    ) -> "UpdateExtensionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def undeploy_extension(
        self, id: Optional[str], kept_extension_items: Optional[List[Optional[str]]]
    ) -> "UndeployExtensionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_deployed_extensions(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_deployed_extensions(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_deploy_extension(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
            "version": request.version,
            "item_ids": request.item_ids,
            "applications": request.applications,
            "subsystems": request.subsystems,
            "extension_deployment": request.extension_deployment,
        }

        response = await self.deploy_extension(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_update_extension(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
            "version": request.version,
            "item_ids": request.item_ids,
            "applications": request.applications,
            "subsystems": request.subsystems,
            "extension_deployment": request.extension_deployment,
        }

        response = await self.update_extension(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_undeploy_extension(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
            "kept_extension_items": request.kept_extension_items,
        }

        response = await self.undeploy_extension(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/GetDeployedExtensions": grpclib.const.Handler(
                self.__rpc_get_deployed_extensions,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDeployedExtensionsRequest,
                GetDeployedExtensionsResponse,
            ),
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/DeployExtension": grpclib.const.Handler(
                self.__rpc_deploy_extension,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeployExtensionRequest,
                DeployExtensionResponse,
            ),
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/UpdateExtension": grpclib.const.Handler(
                self.__rpc_update_extension,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateExtensionRequest,
                UpdateExtensionResponse,
            ),
            "/com.coralogix.extensions.v1.ExtensionDeploymentService/UndeployExtension": grpclib.const.Handler(
                self.__rpc_undeploy_extension,
                grpclib.const.Cardinality.UNARY_UNARY,
                UndeployExtensionRequest,
                UndeployExtensionResponse,
            ),
        }
