# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/outgoing_webhooks/v1/audit_log.proto, com/coralogix/outgoing_webhooks/v1/outgoing_webhook.proto, com/coralogix/outgoing_webhooks/v1/outgoing_webhook_service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional
from betterproto.grpc.grpclib_client import MetadataLike

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


class WebhookType(betterproto.Enum):
    UNKNOWN = 0
    GENERIC = 1
    SLACK = 2
    PAGERDUTY = 3
    SEND_LOG = 4
    EMAIL_GROUP = 5
    MICROSOFT_TEAMS = 6
    JIRA = 7
    OPSGENIE = 8
    DEMISTO = 9
    AWS_EVENT_BRIDGE = 10
    IBM_EVENT_NOTIFICATIONS = 11


class GenericWebhookConfigMethodType(betterproto.Enum):
    UNKNOWN = 0
    GET = 1
    POST = 2
    PUT = 3


class SlackConfigDigestType(betterproto.Enum):
    UNKNOWN = 0
    ERROR_AND_CRITICAL_LOGS = 1
    FLOW_ANOMALIES = 2
    SPIKE_ANOMALIES = 3
    DATA_USAGE = 4


class SlackConfigAttachmentType(betterproto.Enum):
    EMPTY = 0
    METRIC_SNAPSHOT = 1
    LOGS = 2


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: Optional[str] = betterproto.string_field(
        1, optional=True, group="_description"
    )


@dataclass(eq=False, repr=False)
class GenericWebhookConfig(betterproto.Message):
    uuid: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    method: "GenericWebhookConfigMethodType" = betterproto.enum_field(2)
    headers: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    payload: Optional[str] = betterproto.message_field(4, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class SlackConfig(betterproto.Message):
    digests: List["SlackConfigDigest"] = betterproto.message_field(1)
    attachments: List["SlackConfigAttachment"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SlackConfigDigest(betterproto.Message):
    type: "SlackConfigDigestType" = betterproto.enum_field(1)
    is_active: Optional[bool] = betterproto.message_field(
        2, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class SlackConfigAttachment(betterproto.Message):
    type: "SlackConfigAttachmentType" = betterproto.enum_field(1)
    is_active: Optional[bool] = betterproto.message_field(
        2, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class PagerDutyConfig(betterproto.Message):
    service_key: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class SendLogConfig(betterproto.Message):
    uuid: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    payload: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class EmailGroupConfig(betterproto.Message):
    email_addresses: List[Optional[str]] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class MicrosoftTeamsConfig(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class JiraConfig(betterproto.Message):
    api_token: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    email: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    project_key: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OpsgenieConfig(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DemistoConfig(betterproto.Message):
    uuid: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    payload: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class AwsEventBridgeConfig(betterproto.Message):
    event_bus_arn: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    detail: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    detail_type: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    source: Optional[str] = betterproto.message_field(4, wraps=betterproto.TYPE_STRING)
    role_name: Optional[str] = betterproto.message_field(
        6, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class IbmEventNotificationsConfig(betterproto.Message):
    event_notifications_instance_id: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    region_id: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    source_id: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    source_name: Optional[str] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OutgoingWebhook(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    type: "WebhookType" = betterproto.enum_field(2)
    name: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    url: Optional[str] = betterproto.message_field(4, wraps=betterproto.TYPE_STRING)
    created_at: datetime = betterproto.message_field(5)
    updated_at: datetime = betterproto.message_field(6)
    external_id: Optional[int] = betterproto.message_field(
        7, wraps=betterproto.TYPE_UINT32
    )
    generic_webhook: "GenericWebhookConfig" = betterproto.message_field(
        100, group="config"
    )
    slack: "SlackConfig" = betterproto.message_field(101, group="config")
    pager_duty: "PagerDutyConfig" = betterproto.message_field(102, group="config")
    send_log: "SendLogConfig" = betterproto.message_field(103, group="config")
    email_group: "EmailGroupConfig" = betterproto.message_field(104, group="config")
    microsoft_teams: "MicrosoftTeamsConfig" = betterproto.message_field(
        105, group="config"
    )
    jira: "JiraConfig" = betterproto.message_field(106, group="config")
    opsgenie: "OpsgenieConfig" = betterproto.message_field(107, group="config")
    demisto: "DemistoConfig" = betterproto.message_field(108, group="config")
    aws_event_bridge: "AwsEventBridgeConfig" = betterproto.message_field(
        109, group="config"
    )
    ibm_event_notifications: "IbmEventNotificationsConfig" = betterproto.message_field(
        110, group="config"
    )


@dataclass(eq=False, repr=False)
class OutgoingWebhookInputData(betterproto.Message):
    type: "WebhookType" = betterproto.enum_field(1)
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    url: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    generic_webhook: "GenericWebhookConfig" = betterproto.message_field(
        100, group="config"
    )
    slack: "SlackConfig" = betterproto.message_field(101, group="config")
    pager_duty: "PagerDutyConfig" = betterproto.message_field(102, group="config")
    send_log: "SendLogConfig" = betterproto.message_field(103, group="config")
    email_group: "EmailGroupConfig" = betterproto.message_field(104, group="config")
    microsoft_teams: "MicrosoftTeamsConfig" = betterproto.message_field(
        105, group="config"
    )
    jira: "JiraConfig" = betterproto.message_field(106, group="config")
    opsgenie: "OpsgenieConfig" = betterproto.message_field(107, group="config")
    demisto: "DemistoConfig" = betterproto.message_field(108, group="config")
    aws_event_bridge: "AwsEventBridgeConfig" = betterproto.message_field(
        109, group="config"
    )
    ibm_event_notifications: "IbmEventNotificationsConfig" = betterproto.message_field(
        110, group="config"
    )


@dataclass(eq=False, repr=False)
class OutgoingWebhookSummary(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    url: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    created_at: datetime = betterproto.message_field(4)
    updated_at: datetime = betterproto.message_field(5)
    external_id: Optional[int] = betterproto.message_field(
        6, wraps=betterproto.TYPE_UINT32
    )


@dataclass(eq=False, repr=False)
class OutgoingWebhookExtendedSummary(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    type: "WebhookType" = betterproto.enum_field(2)
    name: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    url: Optional[str] = betterproto.message_field(4, wraps=betterproto.TYPE_STRING)
    created_at: datetime = betterproto.message_field(5)
    updated_at: datetime = betterproto.message_field(6)
    external_id: Optional[int] = betterproto.message_field(
        7, wraps=betterproto.TYPE_UINT32
    )


@dataclass(eq=False, repr=False)
class OutgoingWebhookDetails(betterproto.Message):
    type: "WebhookType" = betterproto.enum_field(1)
    label: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class ListOutgoingWebhookTypesRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListOutgoingWebhookTypesResponse(betterproto.Message):
    webhooks: List["ListOutgoingWebhookTypesResponseOutgoingWebhookType"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class ListOutgoingWebhookTypesResponseOutgoingWebhookType(betterproto.Message):
    type: "WebhookType" = betterproto.enum_field(1)
    label: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    count: Optional[int] = betterproto.message_field(3, wraps=betterproto.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class GetOutgoingWebhookTypeDetailsRequest(betterproto.Message):
    type: "WebhookType" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class GetOutgoingWebhookTypeDetailsResponse(betterproto.Message):
    details: "OutgoingWebhookDetails" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListOutgoingWebhooksRequest(betterproto.Message):
    type: "WebhookType" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class ListOutgoingWebhooksResponse(betterproto.Message):
    deployed: List["OutgoingWebhookSummary"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListAllOutgoingWebhooksRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListAllOutgoingWebhooksResponse(betterproto.Message):
    deployed: List["OutgoingWebhookExtendedSummary"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetOutgoingWebhookRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class GetOutgoingWebhookResponse(betterproto.Message):
    webhook: "OutgoingWebhook" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CreateOutgoingWebhookRequest(betterproto.Message):
    data: "OutgoingWebhookInputData" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CreateOutgoingWebhookResponse(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class UpdateOutgoingWebhookRequest(betterproto.Message):
    id: str = betterproto.string_field(1)
    data: "OutgoingWebhookInputData" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class UpdateOutgoingWebhookResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeleteOutgoingWebhookRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class DeleteOutgoingWebhookResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class TestOutgoingWebhookRequest(betterproto.Message):
    data: "OutgoingWebhookInputData" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class TestExistingOutgoingWebhookRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class TestOutgoingWebhookResponse(betterproto.Message):
    success: "TestOutgoingWebhookResponseSuccess" = betterproto.message_field(
        1, group="result"
    )
    failure: "TestOutgoingWebhookResponseFailure" = betterproto.message_field(
        2, group="result"
    )


@dataclass(eq=False, repr=False)
class TestOutgoingWebhookResponseSuccess(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class TestOutgoingWebhookResponseFailure(betterproto.Message):
    error_message: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    display_message: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    status_code: Optional[Optional[int]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_UINT32, optional=True, group="_status_code"
    )


@dataclass(eq=False, repr=False)
class ListIbmEventNotificationsInstancesRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListIbmEventNotificationsInstancesResponse(betterproto.Message):
    instances: List[
        "ListIbmEventNotificationsInstancesResponseEventNotificationsInstance"
    ] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListIbmEventNotificationsInstancesResponseEventNotificationsInstance(
    betterproto.Message
):
    instance_id: str = betterproto.string_field(1)
    region_id: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    crn: str = betterproto.string_field(4)
    is_used: bool = betterproto.bool_field(5)


class OutgoingWebhooksServiceStub(betterproto.ServiceStub):
    async def list_outgoing_webhook_types(self, metadata: Optional[
        MetadataLike] = None) -> "ListOutgoingWebhookTypesResponse":

        request = ListOutgoingWebhookTypesRequest()

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListOutgoingWebhookTypes",
            request,
            ListOutgoingWebhookTypesResponse, metadata=metadata
        )

    async def get_outgoing_webhook_type_details(
            self, *, type: "WebhookType" = 0
    ) -> "GetOutgoingWebhookTypeDetailsResponse":

        request = GetOutgoingWebhookTypeDetailsRequest()
        request.type = type

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/GetOutgoingWebhookTypeDetails",
            request,
            GetOutgoingWebhookTypeDetailsResponse,
        )

    async def list_outgoing_webhooks(
            self,
            *,
            metadata: Optional[MetadataLike] = None,
            type: "WebhookType" = 0
    ) -> "ListOutgoingWebhooksResponse":

        request = ListOutgoingWebhooksRequest()
        request.type = type

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListOutgoingWebhooks",
            request,
            ListOutgoingWebhooksResponse, metadata=metadata
        )

    async def list_all_outgoing_webhooks(self) -> "ListAllOutgoingWebhooksResponse":

        request = ListAllOutgoingWebhooksRequest()

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListAllOutgoingWebhooks",
            request,
            ListAllOutgoingWebhooksResponse,
        )

    async def get_outgoing_webhook(
            self, *, metadata: Optional[MetadataLike] = None, id: Optional[str] = None
    ) -> "GetOutgoingWebhookResponse":

        request = GetOutgoingWebhookRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/GetOutgoingWebhook",
            request,
            GetOutgoingWebhookResponse, metadata=metadata
        )

    async def create_outgoing_webhook(
            self, *, data: "OutgoingWebhookInputData" = None
    ) -> "CreateOutgoingWebhookResponse":

        request = CreateOutgoingWebhookRequest()
        if data is not None:
            request.data = data

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/CreateOutgoingWebhook",
            request,
            CreateOutgoingWebhookResponse,
        )

    async def update_outgoing_webhook(
            self, *, id: str = "", metadata: Optional[MetadataLike] = None, data: "OutgoingWebhookInputData" = None
    ) -> "UpdateOutgoingWebhookResponse":

        request = UpdateOutgoingWebhookRequest()
        request.id = id
        if data is not None:
            request.data = data

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/UpdateOutgoingWebhook",
            request,
            UpdateOutgoingWebhookResponse, metadata=metadata
        )

    async def delete_outgoing_webhook(
            self, *, id: Optional[str] = None
    ) -> "DeleteOutgoingWebhookResponse":

        request = DeleteOutgoingWebhookRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/DeleteOutgoingWebhook",
            request,
            DeleteOutgoingWebhookResponse,
        )

    async def test_outgoing_webhook(
            self, *, data: "OutgoingWebhookInputData" = None
    ) -> "TestOutgoingWebhookResponse":

        request = TestOutgoingWebhookRequest()
        if data is not None:
            request.data = data

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/TestOutgoingWebhook",
            request,
            TestOutgoingWebhookResponse,
        )

    async def test_existing_outgoing_webhook(
            self, *, id: Optional[str] = None
    ) -> "TestOutgoingWebhookResponse":

        request = TestExistingOutgoingWebhookRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/TestExistingOutgoingWebhook",
            request,
            TestOutgoingWebhookResponse,
        )

    async def list_ibm_event_notifications_instances(
            self,
    ) -> "ListIbmEventNotificationsInstancesResponse":

        request = ListIbmEventNotificationsInstancesRequest()

        return await self._unary_unary(
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListIbmEventNotificationsInstances",
            request,
            ListIbmEventNotificationsInstancesResponse,
        )


class OutgoingWebhooksServiceBase(ServiceBase):

    async def list_outgoing_webhook_types(self) -> "ListOutgoingWebhookTypesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_outgoing_webhook_type_details(
            self, type: "WebhookType"
    ) -> "GetOutgoingWebhookTypeDetailsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_outgoing_webhooks(
            self, type: "WebhookType"
    ) -> "ListOutgoingWebhooksResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_all_outgoing_webhooks(self) -> "ListAllOutgoingWebhooksResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_outgoing_webhook(
            self, id: Optional[str]
    ) -> "GetOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_outgoing_webhook(
            self, data: "OutgoingWebhookInputData"
    ) -> "CreateOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_outgoing_webhook(
            self, id: str, data: "OutgoingWebhookInputData"
    ) -> "UpdateOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_outgoing_webhook(
            self, id: Optional[str]
    ) -> "DeleteOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def test_outgoing_webhook(
            self, data: "OutgoingWebhookInputData"
    ) -> "TestOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def test_existing_outgoing_webhook(
            self, id: Optional[str]
    ) -> "TestOutgoingWebhookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_ibm_event_notifications_instances(
            self,
    ) -> "ListIbmEventNotificationsInstancesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_list_outgoing_webhook_types(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.list_outgoing_webhook_types(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_outgoing_webhook_type_details(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "type": request.type,
        }

        response = await self.get_outgoing_webhook_type_details(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_list_outgoing_webhooks(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "type": request.type,
        }

        response = await self.list_outgoing_webhooks(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_list_all_outgoing_webhooks(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.list_all_outgoing_webhooks(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_outgoing_webhook(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.get_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_create_outgoing_webhook(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "data": request.data,
        }

        response = await self.create_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_update_outgoing_webhook(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
            "data": request.data,
        }

        response = await self.update_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_delete_outgoing_webhook(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.delete_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_test_outgoing_webhook(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "data": request.data,
        }

        response = await self.test_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_test_existing_outgoing_webhook(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.test_existing_outgoing_webhook(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_list_ibm_event_notifications_instances(
            self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.list_ibm_event_notifications_instances(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListOutgoingWebhookTypes": grpclib.const.Handler(
                self.__rpc_list_outgoing_webhook_types,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListOutgoingWebhookTypesRequest,
                ListOutgoingWebhookTypesResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/GetOutgoingWebhookTypeDetails": grpclib.const.Handler(
                self.__rpc_get_outgoing_webhook_type_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetOutgoingWebhookTypeDetailsRequest,
                GetOutgoingWebhookTypeDetailsResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListOutgoingWebhooks": grpclib.const.Handler(
                self.__rpc_list_outgoing_webhooks,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListOutgoingWebhooksRequest,
                ListOutgoingWebhooksResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListAllOutgoingWebhooks": grpclib.const.Handler(
                self.__rpc_list_all_outgoing_webhooks,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListAllOutgoingWebhooksRequest,
                ListAllOutgoingWebhooksResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/GetOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_get_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetOutgoingWebhookRequest,
                GetOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/CreateOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_create_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateOutgoingWebhookRequest,
                CreateOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/UpdateOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_update_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateOutgoingWebhookRequest,
                UpdateOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/DeleteOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_delete_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteOutgoingWebhookRequest,
                DeleteOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/TestOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_test_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                TestOutgoingWebhookRequest,
                TestOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/TestExistingOutgoingWebhook": grpclib.const.Handler(
                self.__rpc_test_existing_outgoing_webhook,
                grpclib.const.Cardinality.UNARY_UNARY,
                TestExistingOutgoingWebhookRequest,
                TestOutgoingWebhookResponse,
            ),
            "/com.coralogix.outgoing_webhooks.v1.OutgoingWebhooksService/ListIbmEventNotificationsInstances": grpclib.const.Handler(
                self.__rpc_list_ibm_event_notifications_instances,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListIbmEventNotificationsInstancesRequest,
                ListIbmEventNotificationsInstancesResponse,
            ),
        }
