# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/enrichment/v1/audit_log.proto, com/coralogix/enrichment/v1/enrichment.proto, com/coralogix/enrichment/v1/enrichment_request_model.proto, com/coralogix/enrichment/v1/enrichment_service.proto, com/coralogix/enrichment/v1/enrichment_type.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List, Optional
from betterproto.grpc.grpclib_client import MetadataLike

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


@dataclass(eq=False, repr=False)
class EnrichmentType(betterproto.Message):
    geo_ip: "GeoIpType" = betterproto.message_field(1, group="type")
    suspicious_ip: "SuspiciousIpType" = betterproto.message_field(2, group="type")
    aws: "AwsType" = betterproto.message_field(3, group="type")
    custom_enrichment: "CustomEnrichmentType" = betterproto.message_field(
        4, group="type"
    )


@dataclass(eq=False, repr=False)
class GeoIpType(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SuspiciousIpType(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class AwsType(betterproto.Message):
    resource_type: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class CustomEnrichmentType(betterproto.Message):
    id: Optional[int] = betterproto.message_field(1, wraps=betterproto.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class Enrichment(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    field_name: str = betterproto.string_field(2)
    enrichment_type: "EnrichmentType" = betterproto.message_field(3)
    enriched_field_name: Optional[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING, optional=True, group="_enriched_field_name"
    )


@dataclass(eq=False, repr=False)
class EnrichmentRequestModel(betterproto.Message):
    field_name: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    enrichment_type: "EnrichmentType" = betterproto.message_field(2)
    enriched_field_name: Optional[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING, optional=True, group="_enriched_field_name"
    )


@dataclass(eq=False, repr=False)
class EnrichmentFieldDefinition(betterproto.Message):
    # the field name of the key targeted for enrichment
    field_name: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    # the field of the enriched key after enrichment
    enriched_field_name: Optional[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING, optional=True, group="_enriched_field_name"
    )


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetEnrichmentLimitRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetEnrichmentLimitResponse(betterproto.Message):
    limit: int = betterproto.uint32_field(1)
    used: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class GetEnrichmentsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetEnrichmentsResponse(betterproto.Message):
    enrichments: List["Enrichment"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AddEnrichmentsRequest(betterproto.Message):
    request_enrichments: List["EnrichmentRequestModel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AddEnrichmentsResponse(betterproto.Message):
    enrichments: List["Enrichment"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RemoveEnrichmentsRequest(betterproto.Message):
    enrichment_ids: List[Optional[int]] = betterproto.message_field(
        1, wraps=betterproto.TYPE_UINT32
    )


@dataclass(eq=False, repr=False)
class RemoveEnrichmentsResponse(betterproto.Message):
    remaining_enrichments: List["Enrichment"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AtomicOverwriteEnrichmentsRequest(betterproto.Message):
    """
    Deletes all enrichments of the given type and replaces them with the new
    ones
    """

    enrichment_type: "EnrichmentType" = betterproto.message_field(1)
    enrichment_fields: List["EnrichmentFieldDefinition"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AtomicOverwriteEnrichmentsResponse(betterproto.Message):
    enrichments: List["Enrichment"] = betterproto.message_field(1)


class EnrichmentServiceStub(betterproto.ServiceStub):
    async def get_enrichments(self, metadata: Optional[MetadataLike] = None) -> "GetEnrichmentsResponse":

        request = GetEnrichmentsRequest()

        return await self._unary_unary(
            "/com.coralogix.enrichment.v1.EnrichmentService/GetEnrichments",
            request,
            GetEnrichmentsResponse, metadata=metadata
        )

    async def add_enrichments(
        self, *, request_enrichments: Optional[List["EnrichmentRequestModel"]] = None
    ) -> "AddEnrichmentsResponse":
        request_enrichments = request_enrichments or []

        request = AddEnrichmentsRequest()
        if request_enrichments is not None:
            request.request_enrichments = request_enrichments

        return await self._unary_unary(
            "/com.coralogix.enrichment.v1.EnrichmentService/AddEnrichments",
            request,
            AddEnrichmentsResponse,
        )

    async def remove_enrichments(
        self, *, enrichment_ids: Optional[List[Optional[int]]] = None
    ) -> "RemoveEnrichmentsResponse":
        enrichment_ids = enrichment_ids or []

        request = RemoveEnrichmentsRequest()
        if enrichment_ids is not None:
            request.enrichment_ids = enrichment_ids

        return await self._unary_unary(
            "/com.coralogix.enrichment.v1.EnrichmentService/RemoveEnrichments",
            request,
            RemoveEnrichmentsResponse,
        )

    async def get_enrichment_limit(self) -> "GetEnrichmentLimitResponse":

        request = GetEnrichmentLimitRequest()

        return await self._unary_unary(
            "/com.coralogix.enrichment.v1.EnrichmentService/GetEnrichmentLimit",
            request,
            GetEnrichmentLimitResponse,
        )

    async def atomic_overwrite_enrichments(
        self,
        *,
        enrichment_type: "EnrichmentType" = None,
        enrichment_fields: Optional[List["EnrichmentFieldDefinition"]] = None
    ) -> "AtomicOverwriteEnrichmentsResponse":
        enrichment_fields = enrichment_fields or []

        request = AtomicOverwriteEnrichmentsRequest()
        if enrichment_type is not None:
            request.enrichment_type = enrichment_type
        if enrichment_fields is not None:
            request.enrichment_fields = enrichment_fields

        return await self._unary_unary(
            "/com.coralogix.enrichment.v1.EnrichmentService/AtomicOverwriteEnrichments",
            request,
            AtomicOverwriteEnrichmentsResponse,
        )


class EnrichmentServiceBase(ServiceBase):

    async def get_enrichments(self) -> "GetEnrichmentsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_enrichments(
        self, request_enrichments: Optional[List["EnrichmentRequestModel"]]
    ) -> "AddEnrichmentsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def remove_enrichments(
        self, enrichment_ids: Optional[List[Optional[int]]]
    ) -> "RemoveEnrichmentsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_enrichment_limit(self) -> "GetEnrichmentLimitResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def atomic_overwrite_enrichments(
        self,
        enrichment_type: "EnrichmentType",
        enrichment_fields: Optional[List["EnrichmentFieldDefinition"]],
    ) -> "AtomicOverwriteEnrichmentsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_enrichments(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_enrichments(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_add_enrichments(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "request_enrichments": request.request_enrichments,
        }

        response = await self.add_enrichments(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_remove_enrichments(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "enrichment_ids": request.enrichment_ids,
        }

        response = await self.remove_enrichments(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_enrichment_limit(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_enrichment_limit(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_atomic_overwrite_enrichments(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "enrichment_type": request.enrichment_type,
            "enrichment_fields": request.enrichment_fields,
        }

        response = await self.atomic_overwrite_enrichments(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.enrichment.v1.EnrichmentService/GetEnrichments": grpclib.const.Handler(
                self.__rpc_get_enrichments,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetEnrichmentsRequest,
                GetEnrichmentsResponse,
            ),
            "/com.coralogix.enrichment.v1.EnrichmentService/AddEnrichments": grpclib.const.Handler(
                self.__rpc_add_enrichments,
                grpclib.const.Cardinality.UNARY_UNARY,
                AddEnrichmentsRequest,
                AddEnrichmentsResponse,
            ),
            "/com.coralogix.enrichment.v1.EnrichmentService/RemoveEnrichments": grpclib.const.Handler(
                self.__rpc_remove_enrichments,
                grpclib.const.Cardinality.UNARY_UNARY,
                RemoveEnrichmentsRequest,
                RemoveEnrichmentsResponse,
            ),
            "/com.coralogix.enrichment.v1.EnrichmentService/GetEnrichmentLimit": grpclib.const.Handler(
                self.__rpc_get_enrichment_limit,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetEnrichmentLimitRequest,
                GetEnrichmentLimitResponse,
            ),
            "/com.coralogix.enrichment.v1.EnrichmentService/AtomicOverwriteEnrichments": grpclib.const.Handler(
                self.__rpc_atomic_overwrite_enrichments,
                grpclib.const.Cardinality.UNARY_UNARY,
                AtomicOverwriteEnrichmentsRequest,
                AtomicOverwriteEnrichmentsResponse,
            ),
        }
