# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/alerts/v1/alert.proto, com/coralogix/alerts/v1/alert_active_when.proto, com/coralogix/alerts/v1/alert_condition.proto, com/coralogix/alerts/v1/alert_event.proto, com/coralogix/alerts/v1/alert_filters.proto, com/coralogix/alerts/v1/alert_meta_label.proto, com/coralogix/alerts/v1/alert_notifications.proto, com/coralogix/alerts/v1/alert_service.proto, com/coralogix/alerts/v1/alert_severity.proto, com/coralogix/alerts/v1/alert_snoozed.proto, com/coralogix/alerts/v1/date_time.proto, com/coralogix/alerts/v1/fields_to_update.proto, com/coralogix/alerts/v1/flow_alert.proto, com/coralogix/alerts/v1/tracing_alert.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional
from betterproto.grpc.grpclib_client import MetadataLike

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


class AlertSeverity(betterproto.Enum):
    ALERT_SEVERITY_INFO_OR_UNSPECIFIED = 0
    ALERT_SEVERITY_WARNING = 1
    ALERT_SEVERITY_CRITICAL = 2
    ALERT_SEVERITY_ERROR = 3


class FlowOperator(betterproto.Enum):
    AND = 0
    OR = 1


class Timeframe(betterproto.Enum):
    TIMEFRAME_5_MIN_OR_UNSPECIFIED = 0
    TIMEFRAME_1_MIN = 18
    TIMEFRAME_2_MIN = 19
    TIMEFRAME_10_MIN = 1
    TIMEFRAME_15_MIN = 17
    TIMEFRAME_20_MIN = 2
    TIMEFRAME_30_MIN = 3
    TIMEFRAME_1_H = 4
    TIMEFRAME_2_H = 5
    TIMEFRAME_3_H = 6
    TIMEFRAME_4_H = 7
    TIMEFRAME_6_H = 8
    TIMEFRAME_12_H = 9
    TIMEFRAME_24_H = 10
    TIMEFRAME_36_H = 20
    TIMEFRAME_48_H = 11
    TIMEFRAME_72_H = 12
    TIMEFRAME_1_W = 13
    TIMEFRAME_1_M = 14
    TIMEFRAME_2_M = 15
    TIMEFRAME_3_M = 16


class RelativeTimeframe(betterproto.Enum):
    RELATIVE_TIMEFRAME_HOUR_OR_UNSPECIFIED = 0
    RELATIVE_TIMEFRAME_DAY = 1
    RELATIVE_TIMEFRAME_WEEK = 2
    RELATIVE_TIMEFRAME_MONTH = 3


class CleanupDeadmanDuration(betterproto.Enum):
    CLEANUP_DEADMAN_DURATION_NEVER_OR_UNSPECIFIED = 0
    CLEANUP_DEADMAN_DURATION_5MIN = 1
    CLEANUP_DEADMAN_DURATION_10MIN = 2
    CLEANUP_DEADMAN_DURATION_1H = 3
    CLEANUP_DEADMAN_DURATION_2H = 4
    CLEANUP_DEADMAN_DURATION_6H = 5
    CLEANUP_DEADMAN_DURATION_12H = 6
    CLEANUP_DEADMAN_DURATION_24H = 7


class EvaluationWindow(betterproto.Enum):
    EVALUATION_WINDOW_ROLLING_OR_UNSPECIFIED = 0
    EVALUATION_WINDOW_DYNAMIC = 1


class MetricAlertConditionParametersMetricSource(betterproto.Enum):
    METRIC_SOURCE_LOGS2METRICS_OR_UNSPECIFIED = 0
    METRIC_SOURCE_PROMETHEUS = 1


class MetricAlertConditionParametersArithmeticOperator(betterproto.Enum):
    ARITHMETIC_OPERATOR_AVG_OR_UNSPECIFIED = 0
    ARITHMETIC_OPERATOR_MIN = 1
    ARITHMETIC_OPERATOR_MAX = 2
    ARITHMETIC_OPERATOR_SUM = 3
    ARITHMETIC_OPERATOR_COUNT = 4
    ARITHMETIC_OPERATOR_PERCENTILE = 5


class AlertFiltersLogSeverity(betterproto.Enum):
    LOG_SEVERITY_DEBUG_OR_UNSPECIFIED = 0
    LOG_SEVERITY_VERBOSE = 1
    LOG_SEVERITY_INFO = 2
    LOG_SEVERITY_WARNING = 3
    LOG_SEVERITY_ERROR = 4
    LOG_SEVERITY_CRITICAL = 5


class AlertFiltersFilterType(betterproto.Enum):
    FILTER_TYPE_TEXT_OR_UNSPECIFIED = 0
    FILTER_TYPE_TEMPLATE = 1
    FILTER_TYPE_RATIO = 2
    FILTER_TYPE_UNIQUE_COUNT = 3
    FILTER_TYPE_TIME_RELATIVE = 4
    FILTER_TYPE_METRIC = 5
    FILTER_TYPE_TRACING = 6
    FILTER_TYPE_FLOW = 7


class DayOfWeek(betterproto.Enum):
    DAY_OF_WEEK_MONDAY_OR_UNSPECIFIED = 0
    DAY_OF_WEEK_TUESDAY = 1
    DAY_OF_WEEK_WEDNESDAY = 2
    DAY_OF_WEEK_THURSDAY = 3
    DAY_OF_WEEK_FRIDAY = 4
    DAY_OF_WEEK_SATURDAY = 5
    DAY_OF_WEEK_SUNDAY = 6


class AlertEventAlertEventType(betterproto.Enum):
    ALERT_EVENT_TYPE_UNSPECIFIED = 0
    ALERT_EVENT_TYPE_USER_ALERT = 1
    ALERT_EVENT_TYPE_ANOMALY = 2
    ALERT_EVENT_TYPE_RATIO = 3
    ALERT_EVENT_TYPE_NEW_VALUE = 4
    ALERT_EVENT_TYPE_UNIQUE_COUNT = 5
    ALERT_EVENT_TYPE_TIME_RELATIVE = 6
    ALERT_EVENT_TYPE_METRIC = 7
    ALERT_EVENT_TYPE_FLOW = 8


class AlertEventAlertEventSubType(betterproto.Enum):
    ALERT_EVENT_SUB_TYPE_UNSPECIFIED = 0
    ALERT_EVENT_SUB_TYPE_FLOW = 2
    ALERT_EVENT_SUB_TYPE_VOLUME = 3


class FieldsToUpdate(betterproto.Enum):
    FIELDS_TO_UPDATE_UNSUPPORTED_OR_UNSPECIFIED = 0
    FIELDS_TO_UPDATE_GROUP_BY = 1
    FIELDS_TO_UPDATE_ACTIVE_WHEN = 2


class AlertEventCountType(betterproto.Enum):
    ALERT_EVENT_COUNT_TYPE_UNSPECIFIED = 0
    ALERT_EVENT_COUNT_TYPE_ALERT = 1
    ALERT_EVENT_COUNT_TYPE_ANOMALY = 2


@dataclass(eq=False, repr=False)
class MetaLabel(betterproto.Message):
    key: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    value: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class FlowStage(betterproto.Message):
    groups: List["FlowGroup"] = betterproto.message_field(1)
    timeframe: "FlowTimeframe" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class FlowAlert(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    not_: Optional[bool] = betterproto.message_field(2, wraps=betterproto.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class FlowAlerts(betterproto.Message):
    op: "FlowOperator" = betterproto.enum_field(1)
    values: List["FlowAlert"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class FlowGroup(betterproto.Message):
    alerts: "FlowAlerts" = betterproto.message_field(1)
    next_op: "FlowOperator" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class FlowTimeframe(betterproto.Message):
    ms: Optional[int] = betterproto.message_field(1, wraps=betterproto.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class AlertCondition(betterproto.Message):
    immediate: "ImmediateCondition" = betterproto.message_field(1, group="condition")
    less_than: "LessThanCondition" = betterproto.message_field(2, group="condition")
    more_than: "MoreThanCondition" = betterproto.message_field(3, group="condition")
    more_than_usual: "MoreThanUsualCondition" = betterproto.message_field(
        4, group="condition"
    )
    new_value: "NewValueCondition" = betterproto.message_field(5, group="condition")
    flow: "FlowCondition" = betterproto.message_field(6, group="condition")
    unique_count: "UniqueCountCondition" = betterproto.message_field(
        7, group="condition"
    )
    less_than_usual: "LessThanUsualCondition" = betterproto.message_field(
        8, group="condition"
    )
    more_than_or_equal: "MoreThanOrEqualCondition" = betterproto.message_field(
        9, group="condition"
    )
    less_than_or_equal: "LessThanOrEqualCondition" = betterproto.message_field(
        10, group="condition"
    )


@dataclass(eq=False, repr=False)
class ImmediateCondition(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class LessThanCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class LessThanOrEqualCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class MoreThanCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)
    evaluation_window: Optional["EvaluationWindow"] = betterproto.enum_field(
        2, optional=True, group="_evaluation_window"
    )


@dataclass(eq=False, repr=False)
class MoreThanOrEqualCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)
    evaluation_window: Optional["EvaluationWindow"] = betterproto.enum_field(
        2, optional=True, group="_evaluation_window"
    )


@dataclass(eq=False, repr=False)
class MoreThanUsualCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class LessThanUsualCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class NewValueCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class UniqueCountCondition(betterproto.Message):
    parameters: "ConditionParameters" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class FlowCondition(betterproto.Message):
    stages: List["FlowStage"] = betterproto.message_field(1)
    parameters: Optional["ConditionParameters"] = betterproto.message_field(
        2, optional=True, group="_parameters"
    )
    enforce_suppression: Optional[bool] = betterproto.message_field(
        3, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class ConditionParameters(betterproto.Message):
    threshold: Optional[float] = betterproto.message_field(
        1, wraps=betterproto.TYPE_DOUBLE
    )
    timeframe: "Timeframe" = betterproto.enum_field(2)
    group_by: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    metric_alert_parameters: "MetricAlertConditionParameters" = (
        betterproto.message_field(4)
    )
    metric_alert_promql_parameters: "MetricAlertPromqlConditionParameters" = (
        betterproto.message_field(5)
    )
    notify_on_resolved: Optional[bool] = betterproto.message_field(
        6, wraps=betterproto.TYPE_BOOL
    )
    ignore_infinity: Optional[bool] = betterproto.message_field(
        7, wraps=betterproto.TYPE_BOOL
    )
    relative_timeframe: "RelativeTimeframe" = betterproto.enum_field(8)
    notify_group_by_only_alerts: Optional[bool] = betterproto.message_field(
        9, wraps=betterproto.TYPE_BOOL
    )
    notify_per_group_by_value: Optional[bool] = betterproto.message_field(
        10, wraps=betterproto.TYPE_BOOL
    )
    cardinality_fields: List[Optional[str]] = betterproto.message_field(
        11, wraps=betterproto.TYPE_STRING
    )
    max_unique_count_values_for_group_by_key: Optional[int] = betterproto.message_field(
        12, wraps=betterproto.TYPE_UINT32
    )
    related_extended_data: Optional["RelatedExtendedData"] = betterproto.message_field(
        13, optional=True, group="_related_extended_data"
    )


@dataclass(eq=False, repr=False)
class MetricAlertConditionParameters(betterproto.Message):
    metric_field: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    metric_source: "MetricAlertConditionParametersMetricSource" = (
        betterproto.enum_field(2)
    )
    arithmetic_operator: "MetricAlertConditionParametersArithmeticOperator" = (
        betterproto.enum_field(3)
    )
    arithmetic_operator_modifier: Optional[int] = betterproto.message_field(
        4, wraps=betterproto.TYPE_UINT32
    )
    sample_threshold_percentage: Optional[int] = betterproto.message_field(
        5, wraps=betterproto.TYPE_UINT32
    )
    non_null_percentage: Optional[int] = betterproto.message_field(
        6, wraps=betterproto.TYPE_UINT32
    )
    swap_null_values: Optional[bool] = betterproto.message_field(
        7, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class MetricAlertPromqlConditionParameters(betterproto.Message):
    promql_text: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    arithmetic_operator_modifier: Optional[int] = betterproto.message_field(
        2, wraps=betterproto.TYPE_UINT32
    )
    sample_threshold_percentage: Optional[int] = betterproto.message_field(
        3, wraps=betterproto.TYPE_UINT32
    )
    non_null_percentage: Optional[int] = betterproto.message_field(
        4, wraps=betterproto.TYPE_UINT32
    )
    swap_null_values: Optional[bool] = betterproto.message_field(
        5, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class RelatedExtendedData(betterproto.Message):
    cleanup_deadman_duration: Optional["CleanupDeadmanDuration"] = (
        betterproto.enum_field(1, optional=True, group="_cleanup_deadman_duration")
    )
    should_trigger_deadman: Optional[Optional[bool]] = betterproto.message_field(
        2, wraps=betterproto.TYPE_BOOL, optional=True, group="_should_trigger_deadman"
    )


@dataclass(eq=False, repr=False)
class AlertNotifications(betterproto.Message):
    emails: List[Optional[str]] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    integrations: List[Optional[str]] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class AlertFilters(betterproto.Message):
    severities: List["AlertFiltersLogSeverity"] = betterproto.enum_field(1)
    metadata: "AlertFiltersMetadataFilters" = betterproto.message_field(2)
    alias: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    text: Optional[str] = betterproto.message_field(4, wraps=betterproto.TYPE_STRING)
    ratio_alerts: List["AlertFiltersRatioAlert"] = betterproto.message_field(5)
    filter_type: "AlertFiltersFilterType" = betterproto.enum_field(6)


@dataclass(eq=False, repr=False)
class AlertFiltersMetadataFilters(betterproto.Message):
    categories: List[Optional[str]] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    applications: List[Optional[str]] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    computers: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    classes: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )
    methods: List[Optional[str]] = betterproto.message_field(
        6, wraps=betterproto.TYPE_STRING
    )
    ip_addresses: List[Optional[str]] = betterproto.message_field(
        7, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class AlertFiltersRatioAlert(betterproto.Message):
    alias: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    text: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    severities: List["AlertFiltersLogSeverity"] = betterproto.enum_field(3)
    applications: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        5, wraps=betterproto.TYPE_STRING
    )
    group_by: List[Optional[str]] = betterproto.message_field(
        6, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class Date(betterproto.Message):
    year: int = betterproto.int32_field(1)
    month: int = betterproto.int32_field(2)
    day: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class Time(betterproto.Message):
    hours: int = betterproto.int32_field(1)
    minutes: int = betterproto.int32_field(2)
    seconds: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class AlertActiveWhen(betterproto.Message):
    timeframes: List["AlertActiveTimeframe"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AlertActiveTimeframe(betterproto.Message):
    days_of_week: List["DayOfWeek"] = betterproto.enum_field(1)
    range: "TimeRange" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class TimeRange(betterproto.Message):
    start: "Time" = betterproto.message_field(1)
    end: "Time" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class TracingAlert(betterproto.Message):
    condition_latency: int = betterproto.uint32_field(1)
    field_filters: List["FilterData"] = betterproto.message_field(2)
    tag_filters: List["FilterData"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class FilterData(betterproto.Message):
    field: str = betterproto.string_field(1)
    filters: List["Filters"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Filters(betterproto.Message):
    values: List[str] = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Alert(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    description: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    is_active: Optional[bool] = betterproto.message_field(
        4, wraps=betterproto.TYPE_BOOL
    )
    severity: "AlertSeverity" = betterproto.enum_field(5)
    expiration: "Date" = betterproto.message_field(6)
    condition: "AlertCondition" = betterproto.message_field(7)
    notifications: "AlertNotifications" = betterproto.message_field(8)
    filters: "AlertFilters" = betterproto.message_field(9)
    notify_every: Optional[float] = betterproto.message_field(
        10, wraps=betterproto.TYPE_DOUBLE
    )
    active_when: "AlertActiveWhen" = betterproto.message_field(11)
    notification_payload_filters: List[Optional[str]] = betterproto.message_field(
        12, wraps=betterproto.TYPE_STRING
    )
    meta_labels: List["MetaLabel"] = betterproto.message_field(13)
    meta_labels_strings: List[Optional[str]] = betterproto.message_field(
        14, wraps=betterproto.TYPE_STRING
    )
    tracing_alert: "TracingAlert" = betterproto.message_field(15)
    unique_identifier: Optional[str] = betterproto.message_field(
        16, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class AlertSnoozed(betterproto.Message):
    user_id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    until: datetime = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AlertEvent(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    type: "AlertEventAlertEventType" = betterproto.enum_field(2)
    alert_id: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    company_id: Optional[str] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    severity: "AlertSeverity" = betterproto.enum_field(5)
    subsystem: Optional[str] = betterproto.message_field(
        6, wraps=betterproto.TYPE_STRING
    )
    application: Optional[str] = betterproto.message_field(
        7, wraps=betterproto.TYPE_STRING
    )
    occurred_on: datetime = betterproto.message_field(8)
    name: Optional[str] = betterproto.message_field(9, wraps=betterproto.TYPE_STRING)
    snoozed: "AlertSnoozed" = betterproto.message_field(10)
    sub_type: "AlertEventAlertEventSubType" = betterproto.enum_field(11)


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetAlertRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class GetAlertResponse(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetAlertByUniqueIdRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class GetAlertByUniqueIdResponse(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CreateAlertRequest(betterproto.Message):
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    description: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    is_active: Optional[bool] = betterproto.message_field(
        4, wraps=betterproto.TYPE_BOOL
    )
    severity: "AlertSeverity" = betterproto.enum_field(5)
    expiration: "Date" = betterproto.message_field(6)
    condition: "AlertCondition" = betterproto.message_field(7)
    notifications: "AlertNotifications" = betterproto.message_field(8)
    filters: "AlertFilters" = betterproto.message_field(9)
    notify_every: Optional[float] = betterproto.message_field(
        10, wraps=betterproto.TYPE_DOUBLE
    )
    active_when: "AlertActiveWhen" = betterproto.message_field(11)
    notification_payload_filters: List[Optional[str]] = betterproto.message_field(
        12, wraps=betterproto.TYPE_STRING
    )
    meta_labels: List["MetaLabel"] = betterproto.message_field(13)
    meta_labels_strings: List[Optional[str]] = betterproto.message_field(
        14, wraps=betterproto.TYPE_STRING
    )
    tracing_alert: "TracingAlert" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class CreateAlertResponse(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetAlertModelMappingRequest(betterproto.Message):
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    description: Optional[str] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    is_active: Optional[bool] = betterproto.message_field(
        4, wraps=betterproto.TYPE_BOOL
    )
    severity: "AlertSeverity" = betterproto.enum_field(5)
    expiration: "Date" = betterproto.message_field(6)
    condition: "AlertCondition" = betterproto.message_field(7)
    notifications: "AlertNotifications" = betterproto.message_field(8)
    filters: "AlertFilters" = betterproto.message_field(9)
    notify_every: Optional[float] = betterproto.message_field(
        10, wraps=betterproto.TYPE_DOUBLE
    )
    active_when: "AlertActiveWhen" = betterproto.message_field(11)
    notification_payload_filters: List[Optional[str]] = betterproto.message_field(
        12, wraps=betterproto.TYPE_STRING
    )
    meta_labels: List["MetaLabel"] = betterproto.message_field(13)
    meta_labels_strings: List[Optional[str]] = betterproto.message_field(
        14, wraps=betterproto.TYPE_STRING
    )
    tracing_alert: "TracingAlert" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class GetAlertModelMappingResponse(betterproto.Message):
    alert_definition: "betterproto_lib_google_protobuf.Struct" = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class UpdateAlertRequest(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)
    fields_to_update: List["FieldsToUpdate"] = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class UpdateAlertResponse(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class UpdateAlertByUniqueIdRequest(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)
    fields_to_update: List["FieldsToUpdate"] = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class UpdateAlertByUniqueIdResponse(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)
    fields_to_update: List["FieldsToUpdate"] = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class DeleteAlertRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class DeleteAlertResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeleteAlertByUniqueIdRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class DeleteAlertByUniqueIdResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetAlertEventsRequest(betterproto.Message):
    from_: datetime = betterproto.message_field(2)
    to: datetime = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class GetAlertEventsResponse(betterproto.Message):
    events: List["AlertEvent"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetAlertsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetAlertsResponse(betterproto.Message):
    alerts: List["Alert"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ValidateAlertRequest(betterproto.Message):
    alert: "Alert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ValidateAlertResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetAlertEventsCountBySeverityRequest(betterproto.Message):
    from_: datetime = betterproto.message_field(1)
    to: datetime = betterproto.message_field(2)
    applications: List[Optional[str]] = betterproto.message_field(
        3, wraps=betterproto.TYPE_STRING
    )
    subsystems: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class GetAlertEventsCountBySeverityResponse(betterproto.Message):
    event_counts: List["AlertEventsCountBySeverity"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AlertEventsCountBySeverity(betterproto.Message):
    severity: "AlertSeverity" = betterproto.enum_field(1)
    type: "AlertEventCountType" = betterproto.enum_field(2)
    sub_type: "AlertEventAlertEventSubType" = betterproto.enum_field(3)
    count: Optional[int] = betterproto.message_field(4, wraps=betterproto.TYPE_INT32)


@dataclass(eq=False, repr=False)
class GetCompanyAlertsLimitRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetCompanyAlertsLimitResponse(betterproto.Message):
    company_id: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    limit: Optional[int] = betterproto.message_field(2, wraps=betterproto.TYPE_INT32)
    used: Optional[int] = betterproto.message_field(3, wraps=betterproto.TYPE_INT32)
    dynamic_alert_limit: Optional[int] = betterproto.message_field(
        4, wraps=betterproto.TYPE_INT32
    )
    dynamic_alert_used: Optional[int] = betterproto.message_field(
        5, wraps=betterproto.TYPE_INT32
    )


class AlertServiceStub(betterproto.ServiceStub):
    async def get_alert(self, *, id: Optional[str] = None) -> "GetAlertResponse":

        request = GetAlertRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlert", request, GetAlertResponse
        )

    async def get_alerts(self, metadata: Optional[MetadataLike] = None) -> "GetAlertsResponse":

        request = GetAlertsRequest()

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlerts",
            request,
            GetAlertsResponse, metadata=metadata
        )

    async def get_alert_by_unique_id(
        self, *, id: Optional[str] = None
    ) -> "GetAlertByUniqueIdResponse":

        request = GetAlertByUniqueIdRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlertByUniqueId",
            request,
            GetAlertByUniqueIdResponse,
        )

    async def get_alert_model_mapping(
        self,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        is_active: Optional[bool] = None,
        severity: "AlertSeverity" = 0,
        expiration: "Date" = None,
        condition: "AlertCondition" = None,
        notifications: "AlertNotifications" = None,
        filters: "AlertFilters" = None,
        notify_every: Optional[float] = None,
        active_when: "AlertActiveWhen" = None,
        notification_payload_filters: Optional[List[Optional[str]]] = None,
        meta_labels: Optional[List["MetaLabel"]] = None,
        meta_labels_strings: Optional[List[Optional[str]]] = None,
        tracing_alert: "TracingAlert" = None
    ) -> "GetAlertModelMappingResponse":
        notification_payload_filters = notification_payload_filters or []
        meta_labels = meta_labels or []
        meta_labels_strings = meta_labels_strings or []

        request = GetAlertModelMappingRequest()
        if name is not None:
            request.name = name
        if description is not None:
            request.description = description
        if is_active is not None:
            request.is_active = is_active
        request.severity = severity
        if expiration is not None:
            request.expiration = expiration
        if condition is not None:
            request.condition = condition
        if notifications is not None:
            request.notifications = notifications
        if filters is not None:
            request.filters = filters
        if notify_every is not None:
            request.notify_every = notify_every
        if active_when is not None:
            request.active_when = active_when
        if notification_payload_filters is not None:
            request.notification_payload_filters = notification_payload_filters
        if meta_labels is not None:
            request.meta_labels = meta_labels
        if meta_labels_strings is not None:
            request.meta_labels_strings = meta_labels_strings
        if tracing_alert is not None:
            request.tracing_alert = tracing_alert

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlertModelMapping",
            request,
            GetAlertModelMappingResponse,
        )

    async def create_alert(
        self,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        is_active: Optional[bool] = None,
        severity: "AlertSeverity" = 0,
        expiration: "Date" = None,
        condition: "AlertCondition" = None,
        notifications: "AlertNotifications" = None,
        filters: "AlertFilters" = None,
        notify_every: Optional[float] = None,
        active_when: "AlertActiveWhen" = None,
        notification_payload_filters: Optional[List[Optional[str]]] = None,
        meta_labels: Optional[List["MetaLabel"]] = None,
        meta_labels_strings: Optional[List[Optional[str]]] = None,
        tracing_alert: "TracingAlert" = None
    ) -> "CreateAlertResponse":
        notification_payload_filters = notification_payload_filters or []
        meta_labels = meta_labels or []
        meta_labels_strings = meta_labels_strings or []

        request = CreateAlertRequest()
        if name is not None:
            request.name = name
        if description is not None:
            request.description = description
        if is_active is not None:
            request.is_active = is_active
        request.severity = severity
        if expiration is not None:
            request.expiration = expiration
        if condition is not None:
            request.condition = condition
        if notifications is not None:
            request.notifications = notifications
        if filters is not None:
            request.filters = filters
        if notify_every is not None:
            request.notify_every = notify_every
        if active_when is not None:
            request.active_when = active_when
        if notification_payload_filters is not None:
            request.notification_payload_filters = notification_payload_filters
        if meta_labels is not None:
            request.meta_labels = meta_labels
        if meta_labels_strings is not None:
            request.meta_labels_strings = meta_labels_strings
        if tracing_alert is not None:
            request.tracing_alert = tracing_alert

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/CreateAlert",
            request,
            CreateAlertResponse,
        )

    async def update_alert(
        self,
        *,
        alert: "Alert" = None,
        fields_to_update: Optional[List["FieldsToUpdate"]] = None
    ) -> "UpdateAlertResponse":
        fields_to_update = fields_to_update or []

        request = UpdateAlertRequest()
        if alert is not None:
            request.alert = alert
        request.fields_to_update = fields_to_update

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/UpdateAlert",
            request,
            UpdateAlertResponse,
        )

    async def update_alert_by_unique_id(
        self,
        *,
        alert: "Alert" = None,
        fields_to_update: Optional[List["FieldsToUpdate"]] = None
    ) -> "UpdateAlertByUniqueIdResponse":
        fields_to_update = fields_to_update or []

        request = UpdateAlertByUniqueIdRequest()
        if alert is not None:
            request.alert = alert
        request.fields_to_update = fields_to_update

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/UpdateAlertByUniqueId",
            request,
            UpdateAlertByUniqueIdResponse,
        )

    async def delete_alert(self, *, id: Optional[str] = None) -> "DeleteAlertResponse":

        request = DeleteAlertRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/DeleteAlert",
            request,
            DeleteAlertResponse,
        )

    async def delete_alert_by_unique_id(
        self, *, id: Optional[str] = None
    ) -> "DeleteAlertByUniqueIdResponse":

        request = DeleteAlertByUniqueIdRequest()
        if id is not None:
            request.id = id

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/DeleteAlertByUniqueId",
            request,
            DeleteAlertByUniqueIdResponse,
        )

    async def get_alert_events(
        self, *, from_: datetime = None, to: datetime = None
    ) -> "GetAlertEventsResponse":

        request = GetAlertEventsRequest()
        if from_ is not None:
            request.from_ = from_
        if to is not None:
            request.to = to

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlertEvents",
            request,
            GetAlertEventsResponse,
        )

    async def validate_alert(self, *, alert: "Alert" = None) -> "ValidateAlertResponse":

        request = ValidateAlertRequest()
        if alert is not None:
            request.alert = alert

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/ValidateAlert",
            request,
            ValidateAlertResponse,
        )

    async def get_alert_events_count_by_severity(
        self,
        *,
        from_: datetime = None,
        to: datetime = None,
        applications: Optional[List[Optional[str]]] = None,
        subsystems: Optional[List[Optional[str]]] = None
    ) -> "GetAlertEventsCountBySeverityResponse":
        applications = applications or []
        subsystems = subsystems or []

        request = GetAlertEventsCountBySeverityRequest()
        if from_ is not None:
            request.from_ = from_
        if to is not None:
            request.to = to
        if applications is not None:
            request.applications = applications
        if subsystems is not None:
            request.subsystems = subsystems

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetAlertEventsCountBySeverity",
            request,
            GetAlertEventsCountBySeverityResponse,
        )

    async def get_company_alerts_limit(self) -> "GetCompanyAlertsLimitResponse":

        request = GetCompanyAlertsLimitRequest()

        return await self._unary_unary(
            "/com.coralogix.alerts.v1.AlertService/GetCompanyAlertsLimit",
            request,
            GetCompanyAlertsLimitResponse,
        )


class AlertServiceBase(ServiceBase):

    async def get_alert(self, id: Optional[str]) -> "GetAlertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_alerts(self) -> "GetAlertsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_alert_by_unique_id(
        self, id: Optional[str]
    ) -> "GetAlertByUniqueIdResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_alert_model_mapping(
        self,
        name: Optional[str],
        description: Optional[str],
        is_active: Optional[bool],
        severity: "AlertSeverity",
        expiration: "Date",
        condition: "AlertCondition",
        notifications: "AlertNotifications",
        filters: "AlertFilters",
        notify_every: Optional[float],
        active_when: "AlertActiveWhen",
        notification_payload_filters: Optional[List[Optional[str]]],
        meta_labels: Optional[List["MetaLabel"]],
        meta_labels_strings: Optional[List[Optional[str]]],
        tracing_alert: "TracingAlert",
    ) -> "GetAlertModelMappingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_alert(
        self,
        name: Optional[str],
        description: Optional[str],
        is_active: Optional[bool],
        severity: "AlertSeverity",
        expiration: "Date",
        condition: "AlertCondition",
        notifications: "AlertNotifications",
        filters: "AlertFilters",
        notify_every: Optional[float],
        active_when: "AlertActiveWhen",
        notification_payload_filters: Optional[List[Optional[str]]],
        meta_labels: Optional[List["MetaLabel"]],
        meta_labels_strings: Optional[List[Optional[str]]],
        tracing_alert: "TracingAlert",
    ) -> "CreateAlertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_alert(
        self, alert: "Alert", fields_to_update: Optional[List["FieldsToUpdate"]]
    ) -> "UpdateAlertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_alert_by_unique_id(
        self, alert: "Alert", fields_to_update: Optional[List["FieldsToUpdate"]]
    ) -> "UpdateAlertByUniqueIdResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_alert(self, id: Optional[str]) -> "DeleteAlertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_alert_by_unique_id(
        self, id: Optional[str]
    ) -> "DeleteAlertByUniqueIdResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_alert_events(
        self, from_: datetime, to: datetime
    ) -> "GetAlertEventsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def validate_alert(self, alert: "Alert") -> "ValidateAlertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_alert_events_count_by_severity(
        self,
        from_: datetime,
        to: datetime,
        applications: Optional[List[Optional[str]]],
        subsystems: Optional[List[Optional[str]]],
    ) -> "GetAlertEventsCountBySeverityResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_company_alerts_limit(self) -> "GetCompanyAlertsLimitResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_alert(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.get_alert(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_alerts(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_alerts(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_alert_by_unique_id(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.get_alert_by_unique_id(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_alert_model_mapping(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "name": request.name,
            "description": request.description,
            "is_active": request.is_active,
            "severity": request.severity,
            "expiration": request.expiration,
            "condition": request.condition,
            "notifications": request.notifications,
            "filters": request.filters,
            "notify_every": request.notify_every,
            "active_when": request.active_when,
            "notification_payload_filters": request.notification_payload_filters,
            "meta_labels": request.meta_labels,
            "meta_labels_strings": request.meta_labels_strings,
            "tracing_alert": request.tracing_alert,
        }

        response = await self.get_alert_model_mapping(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_create_alert(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "name": request.name,
            "description": request.description,
            "is_active": request.is_active,
            "severity": request.severity,
            "expiration": request.expiration,
            "condition": request.condition,
            "notifications": request.notifications,
            "filters": request.filters,
            "notify_every": request.notify_every,
            "active_when": request.active_when,
            "notification_payload_filters": request.notification_payload_filters,
            "meta_labels": request.meta_labels,
            "meta_labels_strings": request.meta_labels_strings,
            "tracing_alert": request.tracing_alert,
        }

        response = await self.create_alert(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_update_alert(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "alert": request.alert,
            "fields_to_update": request.fields_to_update,
        }

        response = await self.update_alert(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_update_alert_by_unique_id(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "alert": request.alert,
            "fields_to_update": request.fields_to_update,
        }

        response = await self.update_alert_by_unique_id(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_delete_alert(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.delete_alert(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_delete_alert_by_unique_id(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
        }

        response = await self.delete_alert_by_unique_id(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_alert_events(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "from_": request.from_,
            "to": request.to,
        }

        response = await self.get_alert_events(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_validate_alert(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "alert": request.alert,
        }

        response = await self.validate_alert(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_alert_events_count_by_severity(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "from_": request.from_,
            "to": request.to,
            "applications": request.applications,
            "subsystems": request.subsystems,
        }

        response = await self.get_alert_events_count_by_severity(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_company_alerts_limit(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_company_alerts_limit(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.alerts.v1.AlertService/GetAlert": grpclib.const.Handler(
                self.__rpc_get_alert,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertRequest,
                GetAlertResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetAlerts": grpclib.const.Handler(
                self.__rpc_get_alerts,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertsRequest,
                GetAlertsResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetAlertByUniqueId": grpclib.const.Handler(
                self.__rpc_get_alert_by_unique_id,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertByUniqueIdRequest,
                GetAlertByUniqueIdResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetAlertModelMapping": grpclib.const.Handler(
                self.__rpc_get_alert_model_mapping,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertModelMappingRequest,
                GetAlertModelMappingResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/CreateAlert": grpclib.const.Handler(
                self.__rpc_create_alert,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateAlertRequest,
                CreateAlertResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/UpdateAlert": grpclib.const.Handler(
                self.__rpc_update_alert,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateAlertRequest,
                UpdateAlertResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/UpdateAlertByUniqueId": grpclib.const.Handler(
                self.__rpc_update_alert_by_unique_id,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateAlertByUniqueIdRequest,
                UpdateAlertByUniqueIdResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/DeleteAlert": grpclib.const.Handler(
                self.__rpc_delete_alert,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteAlertRequest,
                DeleteAlertResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/DeleteAlertByUniqueId": grpclib.const.Handler(
                self.__rpc_delete_alert_by_unique_id,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteAlertByUniqueIdRequest,
                DeleteAlertByUniqueIdResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetAlertEvents": grpclib.const.Handler(
                self.__rpc_get_alert_events,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertEventsRequest,
                GetAlertEventsResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/ValidateAlert": grpclib.const.Handler(
                self.__rpc_validate_alert,
                grpclib.const.Cardinality.UNARY_UNARY,
                ValidateAlertRequest,
                ValidateAlertResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetAlertEventsCountBySeverity": grpclib.const.Handler(
                self.__rpc_get_alert_events_count_by_severity,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAlertEventsCountBySeverityRequest,
                GetAlertEventsCountBySeverityResponse,
            ),
            "/com.coralogix.alerts.v1.AlertService/GetCompanyAlertsLimit": grpclib.const.Handler(
                self.__rpc_get_company_alerts_limit,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetCompanyAlertsLimitRequest,
                GetCompanyAlertsLimitResponse,
            ),
        }


import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
