# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/com/coralogix/metrics/metrics-configurator.proto
# plugin: python-betterproto
# This file has been @generated
import warnings
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class RetentionPolicy(betterproto.Message):
    resolution: int = betterproto.int32_field(1)
    retention_days: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class S3Config(betterproto.Message):
    bucket: str = betterproto.string_field(1)
    region: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class IbmConfig(betterproto.Message):
    bucket: str = betterproto.string_field(1)
    region: str = betterproto.string_field(2)
    endpoint: str = betterproto.string_field(3)
    crn: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class IbmConfigV2(betterproto.Message):
    endpoint: str = betterproto.string_field(3)
    """Endpoint to use to access the bucket"""

    crn: str = betterproto.string_field(4)
    """Cloud Object Storage bucket CRN"""

    service_crn: str = betterproto.string_field(5)
    """
    A CRN of a service instance which will be storing data in the bucket. Team
    ID is comming in AuthContext
    """


@dataclass(eq=False, repr=False)
class TenantConfigV2(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)
    retention_policy: "RetentionPolicyRequest" = betterproto.message_field(4)
    ibm: "IbmConfigV2" = betterproto.message_field(5, group="storage_config")
    s3: "S3Config" = betterproto.message_field(6, group="storage_config")
    prefix: str = betterproto.string_field(7)
    disabled: bool = betterproto.bool_field(9)


@dataclass(eq=False, repr=False)
class ConfigureTenantRequest(betterproto.Message):
    retention_policy: "RetentionPolicyRequest" = betterproto.message_field(1)
    ibm: "IbmConfigV2" = betterproto.message_field(2, group="storage_config")
    s3: "S3Config" = betterproto.message_field(3, group="storage_config")


@dataclass(eq=False, repr=False)
class UpdateRequest(betterproto.Message):
    retention_days: Optional[int] = betterproto.uint32_field(
        1, optional=True, group="_retention_days"
    )
    ibm: "IbmConfigV2" = betterproto.message_field(2, group="storage_config")
    s3: "S3Config" = betterproto.message_field(3, group="storage_config")


@dataclass(eq=False, repr=False)
class InternalUpdateRequest(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)
    retention_days: Optional[int] = betterproto.uint32_field(
        2, optional=True, group="_retention_days"
    )
    ibm: "IbmConfigV2" = betterproto.message_field(3, group="storage_config")
    s3: "S3Config" = betterproto.message_field(4, group="storage_config")


@dataclass(eq=False, repr=False)
class ValidateBucketRequest(betterproto.Message):
    ibm: "IbmConfigV2" = betterproto.message_field(1, group="storage_config")
    s3: "S3Config" = betterproto.message_field(2, group="storage_config")


@dataclass(eq=False, repr=False)
class RetentionPolicyRequest(betterproto.Message):
    raw_resolution: int = betterproto.uint32_field(1)
    five_minutes_resolution: int = betterproto.uint32_field(2)
    one_hour_resolution: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class TenantConfig(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)
    bucket_name: str = betterproto.string_field(2)
    region: str = betterproto.string_field(3)
    retention_policy: List["RetentionPolicy"] = betterproto.message_field(4)
    ibm: "IbmConfig" = betterproto.message_field(5, group="storage_config")
    s3: "S3Config" = betterproto.message_field(6, group="storage_config")
    prefix: str = betterproto.string_field(7)
    index_version: int = betterproto.uint32_field(8)
    disabled: bool = betterproto.bool_field(9)

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.is_set("bucket_name"):
            warnings.warn("TenantConfig.bucket_name is deprecated", DeprecationWarning)
        if self.is_set("region"):
            warnings.warn("TenantConfig.region is deprecated", DeprecationWarning)


@dataclass(eq=False, repr=False)
class GetTenantConfigRequest(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class GetTenantConfigResponse(betterproto.Message):
    tenant_config: "TenantConfig" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetTenantConfigResponseV2(betterproto.Message):
    tenant_config: "TenantConfigV2" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListTenantConfigsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListTenantConfigsResponse(betterproto.Message):
    tenant_configs: List["TenantConfig"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class HotStoreConfig(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)
    cluster_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MigrateTenantRequest(betterproto.Message):
    tenant_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class ListHotStoreConfigsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListHotStoreConfigsResponse(betterproto.Message):
    configs: List["HotStoreConfig"] = betterproto.message_field(1)


class MetricsConfiguratorPublicServiceStub(betterproto.ServiceStub):
    async def configure_tenant(
        self,
        configure_tenant_request: "ConfigureTenantRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/ConfigureTenant",
            configure_tenant_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update(
        self,
        update_request: "UpdateRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/Update",
            update_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def validate_bucket(
        self,
        validate_bucket_request: "ValidateBucketRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/ValidateBucket",
            validate_bucket_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_tenant_config(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetTenantConfigResponseV2":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/GetTenantConfig",
            betterproto_lib_google_protobuf_empty,
            GetTenantConfigResponseV2,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def enable_archive(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/EnableArchive",
            betterproto_lib_google_protobuf_empty,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def disable_archive(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/DisableArchive",
            betterproto_lib_google_protobuf_empty,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MetricsConfiguratorServiceStub(betterproto.ServiceStub):
    async def get_tenant_config(
        self,
        get_tenant_config_request: "GetTenantConfigRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetTenantConfigResponse":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/GetTenantConfig",
            get_tenant_config_request,
            GetTenantConfigResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_tenant_configs(
        self,
        list_tenant_configs_request: "ListTenantConfigsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListTenantConfigsResponse":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/ListTenantConfigs",
            list_tenant_configs_request,
            ListTenantConfigsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_host_store_configs(
        self,
        list_hot_store_configs_request: "ListHotStoreConfigsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListHotStoreConfigsResponse":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/ListHostStoreConfigs",
            list_hot_store_configs_request,
            ListHotStoreConfigsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def migrate_tenant(
        self,
        migrate_tenant_request: "MigrateTenantRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/MigrateTenant",
            migrate_tenant_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update(
        self,
        internal_update_request: "InternalUpdateRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Empty":
        return await self._unary_unary(
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/Update",
            internal_update_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MetricsConfiguratorPublicServiceBase(ServiceBase):

    async def configure_tenant(
        self, configure_tenant_request: "ConfigureTenantRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update(
        self, update_request: "UpdateRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def validate_bucket(
        self, validate_bucket_request: "ValidateBucketRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_tenant_config(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "GetTenantConfigResponseV2":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def enable_archive(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def disable_archive(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_configure_tenant(
        self,
        stream: "grpclib.server.Stream[ConfigureTenantRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.configure_tenant(request)
        await stream.send_message(response)

    async def __rpc_update(
        self,
        stream: "grpclib.server.Stream[UpdateRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.update(request)
        await stream.send_message(response)

    async def __rpc_validate_bucket(
        self,
        stream: "grpclib.server.Stream[ValidateBucketRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.validate_bucket(request)
        await stream.send_message(response)

    async def __rpc_get_tenant_config(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, GetTenantConfigResponseV2]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_tenant_config(request)
        await stream.send_message(response)

    async def __rpc_enable_archive(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.enable_archive(request)
        await stream.send_message(response)

    async def __rpc_disable_archive(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.disable_archive(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/ConfigureTenant": grpclib.const.Handler(
                self.__rpc_configure_tenant,
                grpclib.const.Cardinality.UNARY_UNARY,
                ConfigureTenantRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/Update": grpclib.const.Handler(
                self.__rpc_update,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/ValidateBucket": grpclib.const.Handler(
                self.__rpc_validate_bucket,
                grpclib.const.Cardinality.UNARY_UNARY,
                ValidateBucketRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/GetTenantConfig": grpclib.const.Handler(
                self.__rpc_get_tenant_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                GetTenantConfigResponseV2,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/EnableArchive": grpclib.const.Handler(
                self.__rpc_enable_archive,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                betterproto_lib_google_protobuf.Empty,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorPublicService/DisableArchive": grpclib.const.Handler(
                self.__rpc_disable_archive,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                betterproto_lib_google_protobuf.Empty,
            ),
        }


class MetricsConfiguratorServiceBase(ServiceBase):

    async def get_tenant_config(
        self, get_tenant_config_request: "GetTenantConfigRequest"
    ) -> "GetTenantConfigResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_tenant_configs(
        self, list_tenant_configs_request: "ListTenantConfigsRequest"
    ) -> "ListTenantConfigsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_host_store_configs(
        self, list_hot_store_configs_request: "ListHotStoreConfigsRequest"
    ) -> "ListHotStoreConfigsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def migrate_tenant(
        self, migrate_tenant_request: "MigrateTenantRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update(
        self, internal_update_request: "InternalUpdateRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_tenant_config(
        self,
        stream: "grpclib.server.Stream[GetTenantConfigRequest, GetTenantConfigResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_tenant_config(request)
        await stream.send_message(response)

    async def __rpc_list_tenant_configs(
        self,
        stream: "grpclib.server.Stream[ListTenantConfigsRequest, ListTenantConfigsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_tenant_configs(request)
        await stream.send_message(response)

    async def __rpc_list_host_store_configs(
        self,
        stream: "grpclib.server.Stream[ListHotStoreConfigsRequest, ListHotStoreConfigsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_host_store_configs(request)
        await stream.send_message(response)

    async def __rpc_migrate_tenant(
        self,
        stream: "grpclib.server.Stream[MigrateTenantRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.migrate_tenant(request)
        await stream.send_message(response)

    async def __rpc_update(
        self,
        stream: "grpclib.server.Stream[InternalUpdateRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.update(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/GetTenantConfig": grpclib.const.Handler(
                self.__rpc_get_tenant_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetTenantConfigRequest,
                GetTenantConfigResponse,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/ListTenantConfigs": grpclib.const.Handler(
                self.__rpc_list_tenant_configs,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListTenantConfigsRequest,
                ListTenantConfigsResponse,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/ListHostStoreConfigs": grpclib.const.Handler(
                self.__rpc_list_host_store_configs,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListHotStoreConfigsRequest,
                ListHotStoreConfigsResponse,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/MigrateTenant": grpclib.const.Handler(
                self.__rpc_migrate_tenant,
                grpclib.const.Cardinality.UNARY_UNARY,
                MigrateTenantRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
            "/com.coralogix.metrics.metrics_configurator.MetricsConfiguratorService/Update": grpclib.const.Handler(
                self.__rpc_update,
                grpclib.const.Cardinality.UNARY_UNARY,
                InternalUpdateRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
        }
