# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/archive/v2/internal_get_targets.proto, com/coralogix/archive/v2/target.proto, com/coralogix/archive/v2/target_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class IbmBucketType(betterproto.Enum):
    IBM_BUCKET_TYPE_UNSPECIFIED = 0
    IBM_BUCKET_TYPE_EXTERNAL = 1
    IBM_BUCKET_TYPE_INTERNAL = 2


class ArchivingFormatId(betterproto.Enum):
    ARCHIVING_FORMAT_ID_UNSPECIFIED = 0
    ARCHIVING_FORMAT_ID_WIDE_PARQUET_V1 = 1


class OrderBy(betterproto.Enum):
    ORDER_BY_UNSPECIFIED = 0
    ORDER_BY_UPDATED_AT = 1
    ORDER_BY_CREATED_AT = 2
    ORDER_BY_COMPANY_ID = 3


class OrderDirection(betterproto.Enum):
    ORDER_DIRECTION_UNSPECIFIED = 0
    ORDER_DIRECTION_ASC = 1
    ORDER_DIRECTION_DESC = 2


@dataclass(eq=False, repr=False)
class IbmCosTargetSpec(betterproto.Message):
    bucket_crn: str = betterproto.string_field(1)
    endpoint: str = betterproto.string_field(2)
    service_crn: Optional[str] = betterproto.string_field(
        3, optional=True, group="_service_crn"
    )
    bucket_type: Optional["IbmBucketType"] = betterproto.enum_field(
        4, optional=True, group="_bucket_type"
    )


@dataclass(eq=False, repr=False)
class S3TargetSpec(betterproto.Message):
    bucket: str = betterproto.string_field(1)
    region: Optional[str] = betterproto.string_field(2, optional=True, group="_region")


@dataclass(eq=False, repr=False)
class ArchiveSpec(betterproto.Message):
    archiving_format_id: str = betterproto.string_field(1)
    is_active: bool = betterproto.bool_field(2)
    enable_tags: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class Target(betterproto.Message):
    s3: "S3TargetSpec" = betterproto.message_field(1, group="target_spec")
    ibm_cos: "IbmCosTargetSpec" = betterproto.message_field(2, group="target_spec")
    archive_spec: "ArchiveSpec" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class InternalTargetServiceGetTargetsRequest(betterproto.Message):
    filter: Optional["InternalGetTargetsRequestFilter"] = betterproto.message_field(
        1, optional=True, group="_filter"
    )
    order: Optional["TargetResponseOrder"] = betterproto.message_field(
        2, optional=True, group="_order"
    )


@dataclass(eq=False, repr=False)
class InternalTargetServiceGetTargetsResponse(betterproto.Message):
    targets: List["TargetResponse"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class InternalGetTargetsRequestFilter(betterproto.Message):
    company_ids: List[int] = betterproto.uint32_field(1)
    format_id: List["ArchivingFormatId"] = betterproto.enum_field(2)
    is_active: Optional[bool] = betterproto.bool_field(
        3, optional=True, group="_is_active"
    )


@dataclass(eq=False, repr=False)
class TargetResponseOrder(betterproto.Message):
    order_by: Optional["OrderBy"] = betterproto.enum_field(
        1, optional=True, group="_order_by"
    )
    order_direction: Optional["OrderDirection"] = betterproto.enum_field(
        2, optional=True, group="_order_direction"
    )


@dataclass(eq=False, repr=False)
class TargetResponse(betterproto.Message):
    company_id: int = betterproto.uint32_field(1)
    target: Optional["Target"] = betterproto.message_field(
        2, optional=True, group="_target"
    )
    additional_target_properties: Optional["InternalAdditionalTargetProperties"] = (
        betterproto.message_field(
            3, optional=True, group="_additional_target_properties"
        )
    )


@dataclass(eq=False, repr=False)
class InternalAdditionalTargetProperties(betterproto.Message):
    bucket_v2: Optional[str] = betterproto.string_field(
        1, optional=True, group="_bucket_v2"
    )


@dataclass(eq=False, repr=False)
class GetTargetRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetTargetResponse(betterproto.Message):
    target: "Target" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class SetTargetRequest(betterproto.Message):
    is_active: bool = betterproto.bool_field(1)
    s3: "S3TargetSpec" = betterproto.message_field(2, group="target_spec")
    ibm_cos: "IbmCosTargetSpec" = betterproto.message_field(3, group="target_spec")


@dataclass(eq=False, repr=False)
class SetTargetResponse(betterproto.Message):
    target: "Target" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CompanyArchiveConfig(betterproto.Message):
    company_id: int = betterproto.uint32_field(1)
    archive_configured: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ValidateTargetRequest(betterproto.Message):
    is_active: bool = betterproto.bool_field(1)
    s3: "S3TargetSpec" = betterproto.message_field(2, group="target_spec")
    ibm_cos: "IbmCosTargetSpec" = betterproto.message_field(3, group="target_spec")


@dataclass(eq=False, repr=False)
class ValidateTargetResponse(betterproto.Message):
    is_valid: bool = betterproto.bool_field(1)


class TargetServiceStub(betterproto.ServiceStub):
    async def get_target(
        self,
        get_target_request: "GetTargetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetTargetResponse":
        return await self._unary_unary(
            "/com.coralogix.archive.v2.TargetService/GetTarget",
            get_target_request,
            GetTargetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_target(
        self,
        set_target_request: "SetTargetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetTargetResponse":
        return await self._unary_unary(
            "/com.coralogix.archive.v2.TargetService/SetTarget",
            set_target_request,
            SetTargetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def validate_target(
        self,
        validate_target_request: "ValidateTargetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ValidateTargetResponse":
        return await self._unary_unary(
            "/com.coralogix.archive.v2.TargetService/ValidateTarget",
            validate_target_request,
            ValidateTargetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class InternalTargetServiceStub(betterproto.ServiceStub):
    async def get_targets(
        self,
        internal_target_service_get_targets_request: "InternalTargetServiceGetTargetsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "InternalTargetServiceGetTargetsResponse":
        return await self._unary_unary(
            "/com.coralogix.archive.v2.InternalTargetService/GetTargets",
            internal_target_service_get_targets_request,
            InternalTargetServiceGetTargetsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class TargetServiceBase(ServiceBase):

    async def get_target(
        self, get_target_request: "GetTargetRequest"
    ) -> "GetTargetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_target(
        self, set_target_request: "SetTargetRequest"
    ) -> "SetTargetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def validate_target(
        self, validate_target_request: "ValidateTargetRequest"
    ) -> "ValidateTargetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_target(
        self, stream: "grpclib.server.Stream[GetTargetRequest, GetTargetResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_target(request)
        await stream.send_message(response)

    async def __rpc_set_target(
        self, stream: "grpclib.server.Stream[SetTargetRequest, SetTargetResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_target(request)
        await stream.send_message(response)

    async def __rpc_validate_target(
        self,
        stream: "grpclib.server.Stream[ValidateTargetRequest, ValidateTargetResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.validate_target(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.archive.v2.TargetService/GetTarget": grpclib.const.Handler(
                self.__rpc_get_target,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetTargetRequest,
                GetTargetResponse,
            ),
            "/com.coralogix.archive.v2.TargetService/SetTarget": grpclib.const.Handler(
                self.__rpc_set_target,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetTargetRequest,
                SetTargetResponse,
            ),
            "/com.coralogix.archive.v2.TargetService/ValidateTarget": grpclib.const.Handler(
                self.__rpc_validate_target,
                grpclib.const.Cardinality.UNARY_UNARY,
                ValidateTargetRequest,
                ValidateTargetResponse,
            ),
        }


class InternalTargetServiceBase(ServiceBase):

    async def get_targets(
        self,
        internal_target_service_get_targets_request: "InternalTargetServiceGetTargetsRequest",
    ) -> "InternalTargetServiceGetTargetsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_targets(
        self,
        stream: "grpclib.server.Stream[InternalTargetServiceGetTargetsRequest, InternalTargetServiceGetTargetsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_targets(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.archive.v2.InternalTargetService/GetTargets": grpclib.const.Handler(
                self.__rpc_get_targets,
                grpclib.const.Cardinality.UNARY_UNARY,
                InternalTargetServiceGetTargetsRequest,
                InternalTargetServiceGetTargetsResponse,
            ),
        }
