# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/extensions/v1/audit_log.proto, com/coralogix/extensions/v1/extension.proto, com/coralogix/extensions/v1/extension_service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List, Optional
from betterproto.grpc.grpclib_client import MetadataLike

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


@dataclass(eq=False, repr=False)
class AuditLogDescription(betterproto.Message):
    description: Optional[str] = betterproto.string_field(
        1, optional=True, group="_description"
    )


@dataclass(eq=False, repr=False)
class Extension(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    name: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    image: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    dark_mode_image: Optional[str] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    revisions: List["Revision"] = betterproto.message_field(5)
    is_hidden: Optional[bool] = betterproto.message_field(
        6, wraps=betterproto.TYPE_BOOL
    )
    integrations: List[str] = betterproto.string_field(7)
    keywords: List[str] = betterproto.string_field(8)
    deprecation: "Deprecation" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class Revision(betterproto.Message):
    version: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    description: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )
    excerpt: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)
    labels: List[Optional[str]] = betterproto.message_field(
        4, wraps=betterproto.TYPE_STRING
    )
    integration_details: List["IntegrationDetail"] = betterproto.message_field(5)
    summary: "RevisionSummary" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class RevisionSummary(betterproto.Message):
    item_counts: "ItemCounts" = betterproto.message_field(1)
    is_new: Optional[bool] = betterproto.message_field(2, wraps=betterproto.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class ItemCounts(betterproto.Message):
    total: int = betterproto.int32_field(1)
    active: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class IntegrationDetail(betterproto.Message):
    name: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    version: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class Deprecation(betterproto.Message):
    reason: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    replacement: Optional[str] = betterproto.message_field(
        2, wraps=betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class GetAllExtensionsRequest(betterproto.Message):
    include_hidden_extensions: Optional[bool] = betterproto.message_field(
        1, wraps=betterproto.TYPE_BOOL
    )
    filter: "Filter" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Filter(betterproto.Message):
    integrations: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetAllExtensionsResponse(betterproto.Message):
    extensions: List["Extension"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetExtensionRequest(betterproto.Message):
    id: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    include_dashboard_binaries: Optional[bool] = betterproto.message_field(
        2, wraps=betterproto.TYPE_BOOL
    )
    include_testing_revision: Optional[bool] = betterproto.message_field(
        3, wraps=betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class GetExtensionResponse(betterproto.Message):
    extension: "Extension" = betterproto.message_field(1)


class ExtensionServiceStub(betterproto.ServiceStub):
    async def get_all_extensions(
        self,
        *,
        include_hidden_extensions: Optional[bool] = None,
        filter: "Filter" = None
    ) -> "GetAllExtensionsResponse":

        request = GetAllExtensionsRequest()
        if include_hidden_extensions is not None:
            request.include_hidden_extensions = include_hidden_extensions
        if filter is not None:
            request.filter = filter

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionService/GetAllExtensions",
            request,
            GetAllExtensionsResponse,
        )

    async def get_extension(
        self,
        metadata: Optional[MetadataLike] = None,
        *,
        id: Optional[str] = None,
        include_dashboard_binaries: Optional[bool] = None,
        include_testing_revision: Optional[bool] = None
    ) -> "GetExtensionResponse":

        request = GetExtensionRequest()
        if id is not None:
            request.id = id
        if include_dashboard_binaries is not None:
            request.include_dashboard_binaries = include_dashboard_binaries
        if include_testing_revision is not None:
            request.include_testing_revision = include_testing_revision

        return await self._unary_unary(
            "/com.coralogix.extensions.v1.ExtensionService/GetExtension",
            request,
            GetExtensionResponse, metadata=metadata
        )


class ExtensionServiceBase(ServiceBase):

    async def get_all_extensions(
        self, include_hidden_extensions: Optional[bool], filter: "Filter"
    ) -> "GetAllExtensionsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_extension(
        self,
        id: Optional[str],
        include_dashboard_binaries: Optional[bool],
        include_testing_revision: Optional[bool],
    ) -> "GetExtensionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_all_extensions(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "include_hidden_extensions": request.include_hidden_extensions,
            "filter": request.filter,
        }

        response = await self.get_all_extensions(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_get_extension(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "id": request.id,
            "include_dashboard_binaries": request.include_dashboard_binaries,
            "include_testing_revision": request.include_testing_revision,
        }

        response = await self.get_extension(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.extensions.v1.ExtensionService/GetAllExtensions": grpclib.const.Handler(
                self.__rpc_get_all_extensions,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAllExtensionsRequest,
                GetAllExtensionsResponse,
            ),
            "/com.coralogix.extensions.v1.ExtensionService/GetExtension": grpclib.const.Handler(
                self.__rpc_get_extension,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetExtensionRequest,
                GetExtensionResponse,
            ),
        }
