# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: com/coralogix/datausage/v2/data_usage.proto, com/coralogix/datausage/v2/data_usage_service.proto
# plugin: python-betterproto
import warnings
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import AsyncIterator, Dict, List, Optional

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib
from betterproto.grpc.grpclib_client import MetadataLike


class Pillar(betterproto.Enum):
    PILLAR_UNSPECIFIED = 0
    PILLAR_METRICS = 1
    PILLAR_LOGS = 2
    PILLAR_SPANS = 3
    PILLAR_BINARY = 4


class TcoTier(betterproto.Enum):
    TCO_TIER_UNSPECIFIED = 0
    TCO_TIER_LOW = 1
    TCO_TIER_MEDIUM = 2
    TCO_TIER_HIGH = 3
    TCO_TIER_BLOCKED = 4


class Priority(betterproto.Enum):
    PRIORITY_UNSPECIFIED = 0
    PRIORITY_LOW = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_HIGH = 3
    PRIORITY_BLOCKED = 4


class Severity(betterproto.Enum):
    SEVERITY_UNSPECIFIED = 0
    SEVERITY_DEBUG = 1
    SEVERITY_VERBOSE = 2
    SEVERITY_INFO = 3
    SEVERITY_WARNING = 4
    SEVERITY_ERROR = 5
    SEVERITY_CRITICAL = 6


class AggregateBy(betterproto.Enum):
    AGGREGATE_BY_UNSPECIFIED = 0
    AGGREGATE_BY_APPLICATION = 1
    AGGREGATE_BY_SUBSYSTEM = 2
    AGGREGATE_BY_PILLAR = 3
    AGGREGATE_BY_PRIORITY = 4


@dataclass(eq=False, repr=False)
class Team(betterproto.Message):
    id: Optional[int] = betterproto.message_field(2, wraps=betterproto.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class DateRange(betterproto.Message):
    from_date: datetime = betterproto.message_field(1)
    to_date: datetime = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class GenericDimension(betterproto.Message):
    key: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Dimension(betterproto.Message):
    pillar: "Pillar" = betterproto.enum_field(1, group="dimension")
    generic_dimension: "GenericDimension" = betterproto.message_field(
        2, group="dimension"
    )
    tier: "TcoTier" = betterproto.enum_field(3, group="dimension")
    severity: "Severity" = betterproto.enum_field(4, group="dimension")
    priority: "Priority" = betterproto.enum_field(5, group="dimension")

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.tier:
            warnings.warn("Dimension.tier is deprecated", DeprecationWarning)


@dataclass(eq=False, repr=False)
class GetTeamDetailedDataUsageRequest(betterproto.Message):
    # Date request interval
    date_range: "DateRange" = betterproto.message_field(2)
    # Aggregation resolution with minute precision. Do note that to avoid
    # overloading the service we enforce resolution limits that depend on the
    # server configuration. This is configured by the server. This means that,
    # for instance, requests with 1 min resolution for an interval of 30 days
    # will be rejected. Resolution must be between 1 min and date_range interval
    resolution: timedelta = betterproto.message_field(3)
    # List of aggregate parameters. i.e. if AggregateBy is [AGGREGATE_BY_PILLAR,
    # AGGREGATE_BY_PRIORITY], then the response will stream data aggregated by
    # pillar and priority.
    aggregate: List["AggregateBy"] = betterproto.enum_field(4)


@dataclass(eq=False, repr=False)
class GetTeamDetailedDataUsageResponse(betterproto.Message):
    timestamp: datetime = betterproto.message_field(1)
    size_gb: Optional[float] = betterproto.message_field(
        2, wraps=betterproto.TYPE_FLOAT
    )
    units: Optional[float] = betterproto.message_field(3, wraps=betterproto.TYPE_FLOAT)
    dimensions: List["Dimension"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class GetSpansCountRequest(betterproto.Message):
    date_range: "DateRange" = betterproto.message_field(1)
    # Aggregation resolution with second precision. Resolution must be between 1
    # second and date_range interval
    resolution: timedelta = betterproto.message_field(2)
    # Example: (application1 OR application2) AND (subsystem1 OR subsystem2)
    # Match occurs on full match
    filters: Optional["ScopesFilter"] = betterproto.message_field(
        3, optional=True, group="_filters"
    )


@dataclass(eq=False, repr=False)
class ScopesFilter(betterproto.Message):
    application: List[str] = betterproto.string_field(1)
    subsystem: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetSpansCountResponse(betterproto.Message):
    timestamp: datetime = betterproto.message_field(1)
    success_span_count: Optional[int] = betterproto.message_field(
        2, wraps=betterproto.TYPE_INT64
    )
    error_span_count: Optional[int] = betterproto.message_field(
        3, wraps=betterproto.TYPE_INT64
    )


@dataclass(eq=False, repr=False)
class GetDataUsageMetricsExportStatusRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetDataUsageMetricsExportStatusResponse(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class UpdateDataUsageMetricsExportStatusRequest(betterproto.Message):
    enabled: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class UpdateDataUsageMetricsExportStatusResponse(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


class DataUsageServiceStub(betterproto.ServiceStub):
    async def get_team_detailed_data_usage(
        self,
        metadata: Optional[MetadataLike] = None,
        *,
        date_range: "DateRange" = None,
        resolution: timedelta = None,
        aggregate: Optional[List["AggregateBy"]] = None
    ) -> AsyncIterator["GetTeamDetailedDataUsageResponse"]:
        aggregate = aggregate or []

        request = GetTeamDetailedDataUsageRequest()
        if date_range is not None:
            request.date_range = date_range
        if resolution is not None:
            request.resolution = resolution
        request.aggregate = aggregate

        async for response in self._unary_stream(
            "/com.coralogix.datausage.v2.DataUsageService/GetTeamDetailedDataUsage",
            request,
            GetTeamDetailedDataUsageResponse, metadata=metadata
        ):
            yield response

    async def get_spans_count(
        self,
        *,
        date_range: "DateRange" = None,
        resolution: timedelta = None,
        filters: Optional["ScopesFilter"] = None
    ) -> AsyncIterator["GetSpansCountResponse"]:

        request = GetSpansCountRequest()
        if date_range is not None:
            request.date_range = date_range
        if resolution is not None:
            request.resolution = resolution
        if filters is not None:
            request.filters = filters

        async for response in self._unary_stream(
            "/com.coralogix.datausage.v2.DataUsageService/GetSpansCount",
            request,
            GetSpansCountResponse,
        ):
            yield response

    async def get_data_usage_metrics_export_status(
        self,
    ) -> "GetDataUsageMetricsExportStatusResponse":

        request = GetDataUsageMetricsExportStatusRequest()

        return await self._unary_unary(
            "/com.coralogix.datausage.v2.DataUsageService/GetDataUsageMetricsExportStatus",
            request,
            GetDataUsageMetricsExportStatusResponse,
        )

    async def update_data_usage_metrics_export_status(
        self, *, enabled: bool = False
    ) -> "UpdateDataUsageMetricsExportStatusResponse":

        request = UpdateDataUsageMetricsExportStatusRequest()
        request.enabled = enabled

        return await self._unary_unary(
            "/com.coralogix.datausage.v2.DataUsageService/UpdateDataUsageMetricsExportStatus",
            request,
            UpdateDataUsageMetricsExportStatusResponse,
        )


class DataUsageServiceBase(ServiceBase):

    async def get_team_detailed_data_usage(
        self,
        date_range: "DateRange",
        resolution: timedelta,
        aggregate: Optional[List["AggregateBy"]],
    ) -> AsyncIterator["GetTeamDetailedDataUsageResponse"]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_spans_count(
        self,
        date_range: "DateRange",
        resolution: timedelta,
        filters: Optional["ScopesFilter"],
    ) -> AsyncIterator["GetSpansCountResponse"]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_data_usage_metrics_export_status(
        self,
    ) -> "GetDataUsageMetricsExportStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_data_usage_metrics_export_status(
        self, enabled: bool
    ) -> "UpdateDataUsageMetricsExportStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_team_detailed_data_usage(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "date_range": request.date_range,
            "resolution": request.resolution,
            "aggregate": request.aggregate,
        }

        await self._call_rpc_handler_server_stream(
            self.get_team_detailed_data_usage,
            stream,
            request_kwargs,
        )

    async def __rpc_get_spans_count(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "date_range": request.date_range,
            "resolution": request.resolution,
            "filters": request.filters,
        }

        await self._call_rpc_handler_server_stream(
            self.get_spans_count,
            stream,
            request_kwargs,
        )

    async def __rpc_get_data_usage_metrics_export_status(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {}

        response = await self.get_data_usage_metrics_export_status(**request_kwargs)
        await stream.send_message(response)

    async def __rpc_update_data_usage_metrics_export_status(
        self, stream: grpclib.server.Stream
    ) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "enabled": request.enabled,
        }

        response = await self.update_data_usage_metrics_export_status(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/com.coralogix.datausage.v2.DataUsageService/GetTeamDetailedDataUsage": grpclib.const.Handler(
                self.__rpc_get_team_detailed_data_usage,
                grpclib.const.Cardinality.UNARY_STREAM,
                GetTeamDetailedDataUsageRequest,
                GetTeamDetailedDataUsageResponse,
            ),
            "/com.coralogix.datausage.v2.DataUsageService/GetSpansCount": grpclib.const.Handler(
                self.__rpc_get_spans_count,
                grpclib.const.Cardinality.UNARY_STREAM,
                GetSpansCountRequest,
                GetSpansCountResponse,
            ),
            "/com.coralogix.datausage.v2.DataUsageService/GetDataUsageMetricsExportStatus": grpclib.const.Handler(
                self.__rpc_get_data_usage_metrics_export_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDataUsageMetricsExportStatusRequest,
                GetDataUsageMetricsExportStatusResponse,
            ),
            "/com.coralogix.datausage.v2.DataUsageService/UpdateDataUsageMetricsExportStatus": grpclib.const.Handler(
                self.__rpc_update_data_usage_metrics_export_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateDataUsageMetricsExportStatusRequest,
                UpdateDataUsageMetricsExportStatusResponse,
            ),
        }
